config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"

root 'cocktails#index'

  resources :cocktails do
    resources :doses, only: [:new, :create]

  end

  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

    has_attachment :photo

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true

end

app/models/dose.rb
class Dose < ApplicationRecord
 belongs_to :cocktail
 belongs_to :ingredient

 validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses, dependent: :restrict_with_exception

validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :description, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController


  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = @cocktail.doses.build
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Create a new cocktail</h1>
  </div>
</div>

<div class="container">

  <div class="col-md-offset-3 col-md-6">
    <div class="add-form">
      <h2>Name your cocktail</h2>
      <%= simple_form_for(@cocktail) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <div class="form-group">
          <%= f.input :name, label: "cocktail name", input_html: { placeholder: "name" } %>
          <%= f.input :photo, as: :attachinary %>
        </div>
        <div class="form-actions">
          <%= f.submit class: "btn btn-bib" %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<div>
 <div class="banner">

    <h1>Cocktails</h1>
  </div>
</div>

<div class="add-drink">
 <%= link_to 'Add a new cocktail', new_cocktail_path %>
</div>

<div class="cocktail-list">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 text-center">
        <div class="grey-card"


  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path cocktail.photo.path, height: 300, width: 400, crop: :crop %>')">

          <h3><%= cocktail.name %></h3>
        <br>

          <%= link_to 'Show', cocktail %> |
          <%= link_to 'Edit', edit_cocktail_path(cocktail) %> |
          <%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div style="text-align: center">

  </div>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<div class="banner" >
  <h1>
    <%= @cocktail.name %>
  </h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-xs-6">
      <div class="list">
        <h3>Ingredients:</h3>
        <ul>
          <% @cocktail.doses.each do |dose| %>
          <li> <%= dose.description %> <%= dose.ingredient.name %> </li>
          <% end %>
        </ul>
        <%= link_to 'Add an ingredient', new_cocktail_dose_path(@cocktail) %> |
        <%= link_to 'Delete cocktail', @cocktail, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <%= link_to 'Back', cocktails_path %>
        <% if @cocktail.photo? %>
        <%= cl_image_tag @cocktail.photo.path, width: 200, height: 200, crop: :fill %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f|%>

<%= f.input :description %>
<%= f.association :ingredient %>
<%= f.submit %>
<%end  %>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/new.html.erb
<h1>Add New</h1>

<%= render "form" %>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= cloudinary_js_config %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>

  <%= render "shared/navbar" %>
  <%= yield %>
</body>





  </div>
</div>

</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "HOME.jpeg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Button (call-to-action) -->
    <%= link_to "New Cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>